FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /workspace

COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

COPY src src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN apk add --no-cache wget \
    && addgroup -S app \
    && adduser -S app -G app

COPY --from=build /workspace/target/java-control-plane-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

USER app
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
